# Generated by Django 6.1.1 on 2026-09-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_candidate_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
