# Generated by Django 6.1.1 on 2026-09-23 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_whatsapp_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hr_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=180)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('result', models.CharField(default='Success', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('Marketer', 'Marketer'), ('Planner', 'Planner'), ('Architect', 'Architect'), ('Civil Engineer', 'Civil Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Electrical Engineer', 'Electrical Engineer'), ('Software Engineer', 'Software Engineer'), ('Doctor', 'Doctor'), ('Medical Technologist', 'Medical Technologist'), ('Equipment Operator', 'Equipment Operator'), ('Heavy Duty Technician', 'Heavy Duty Technician'), ('Technical Supervisor', 'Technical Supervisor'), ('Administrative Staff', 'Administrative Staff')], max_length=120)),
                ('professionals_required', models.PositiveIntegerField(default=1)),
                ('minimum_qualification', models.CharField(max_length=200)),
                ('certifications', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('required_skills', models.TextField()),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('salary_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under Review'), ('matching', 'Matching Candidates'), ('available', 'Candidates Available'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_requests', to='website.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('eligible', 'Eligible'), ('replaced', 'Replaced'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests_for', to='website.profile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='website.profile')),
                ('replacement_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_assignments', to='website.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='website.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.profile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='website.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Shortlisted', max_length=40)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='website.profile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='website.profile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='website.candidatematch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employer', 'candidate'), name='unique_employer_candidate_shortlist')],
            },
        ),
    ]
