# Generated by Django 5.2.17 on 2026-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_hr_contact_name_profile_industry_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('verification', 'Verification'), ('match', 'Match / Opportunity'), ('shortlist', 'Shortlisted'), ('payment', 'Payment'), ('profile', 'Profile'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
