# Generated by Django 5.2.17 on 2026-09-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profile_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('verifying', 'Under Verification'), ('verified', 'Vetted & Verified'), ('changes', 'Requires Changes'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
