# Generated by Django 6.1.1 on 2026-09-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_recruitmentrequest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatematch',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='website.recruitmentrequest'),
        ),
        migrations.AddConstraint(
            model_name='candidatematch',
            constraint=models.UniqueConstraint(fields=('employer', 'profile', 'request'), name='unique_candidate_match_per_request'),
        ),
    ]
