# Generated by Django 5.2.17 on 2026-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_candidatematch_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatematch',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
