# Generated by Django 5.2.17 on 2026-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
