# Generated by Django 5.2.17 on 2026-09-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_supportmessage_audio_alter_supportmessage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('success', 'Approved'), ('failed', 'Declined')], default='pending', max_length=20),
        ),
    ]
