# Generated by Django 5.2.17 on 2026-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_subscription_expiry_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_size',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hq_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender_role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Target JobSpace')], max_length=10),
        ),
    ]
