# Generated by Django 5.2.17 on 2026-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_employer_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_nature',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry-Level (0–1 year)'), ('junior', 'Junior (1–3 years)'), ('mid', 'Mid-Level (3–5 years)'), ('senior', 'Senior (5–8 years)'), ('principal', 'Principal / Executive (8+ years)')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role_targets',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_headline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='workplace_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
