# Generated by Django 5.2.17 on 2026-10-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_candidate_career_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@targetjobspace.com', max_length=254)),
                ('phone', models.CharField(default='+234 913 618 5082', max_length=30)),
                ('address', models.CharField(default='Bayo Dejonwo Street, Maryland, Lagos.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
