# Generated by Django 5.2.17 on 2026-10-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('career', 'Career Advice'), ('hiring', 'Hiring Tips'), ('industry', 'Industry Insights'), ('workplace', 'Workplace Culture'), ('salary', 'Salary & Negotiation'), ('interview', 'Interview Prep')], default='career', max_length=20)),
                ('excerpt', models.TextField(help_text='Short summary shown on the blog list page.', max_length=300)),
                ('body', models.TextField(help_text='Full article body. Plain text — one blank line = paragraph break.')),
                ('cover_emoji', models.CharField(default='✨', help_text='Emoji used as the cover visual (1–2 emoji).', max_length=8)),
                ('cover_color', models.CharField(default='#d90429', help_text='Accent colour for the card gradient.', max_length=40)),
                ('author', models.CharField(default='Target JobSpace Team', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
