# Generated by Django 5.2.17 on 2026-10-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_emoji',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Landscape image shown on the card and detail page.', null=True, upload_to='blog/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_color',
            field=models.CharField(default='#d90429', help_text='Fallback accent colour when no image is uploaded.', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(max_length=300),
        ),
    ]
