# Generated by Django 5.2.17 on 2026-10-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
