#!/usr/bin/env bash
#
# bootstrap.sh — one-time server setup for JobSpace on AlmaLinux.
#
# Run as root, passing your domain:
#   bash /var/www/jobspace/deploy/bootstrap.sh yourdomain.com
#
# This does the steps that are easy to get subtly wrong by hand: the .env
# file, the systemd unit, the permissions that stop nginx 403ing, and the
# nginx config. It does NOT touch either of the two sites already on this box.
#
# It does NOT obtain a certificate — that is deliberately a separate, manual
# step so that you can watch DNS and certbot succeed before anything else.
#
set -o errexit
set -o nounset
set -o pipefail

DOMAIN="${1:?Usage: bash bootstrap.sh yourdomain.com [www.yourdomain.com]}"
WWW="${2:-$DOMAIN}"
APP=/var/www/jobspace
VENV=$APP/venv

echo "=============================================="
echo " JobSpace setup for: $DOMAIN"
echo "=============================================="

# ── 1. .env ─────────────────────────────────────────────────────────────────
echo ""
echo "==> [1/5] Creating the .env file"

if [ -f "$APP/.env" ]; then
    echo "    .env already exists — leaving it untouched."
    echo "    (delete it first if you really want to regenerate it)"
else
    SECRET=$("$VENV/bin/python" -c \
        "from django.core.management.utils import get_random_secret_key as k; print(k())")

    cat > "$APP/.env" <<EOF
# JobSpace production environment. Generated by deploy/bootstrap.sh
# Contains the secret key and the database password — mode 600, never commit.

SECRET_KEY=$SECRET
DEBUG=False

DATABASE_URL=postgresql://jobspace:CHANGE_ME@127.0.0.1:5432/jobspace

ALLOWED_HOSTS=$DOMAIN,$WWW
CSRF_TRUSTED_ORIGINS=https://$DOMAIN,https://$WWW

# Leave these until HTTPS is confirmed working. Enabling either too early
# causes a redirect loop, and a cached HSTS header cannot be withdrawn for
# a year. See DEPLOY.md step 12.
SECURE_SSL_REDIRECT=False
SECURE_HSTS_SECONDS=0

# Get these from the Flutterwave dashboard BEFORE taking payments.
# An empty WEBHOOK_HASH disables webhook signature verification entirely:
# anyone could then POST a fake "payment successful" to the webhook URL.
FLUTTERWAVE_PUBLIC_KEY=
FLUTTERWAVE_SECRET_KEY=
FLUTTERWAVE_WEBHOOK_HASH=
EOF
    echo "    Created with a freshly generated SECRET_KEY."
fi

chown jobspace:jobspace "$APP/.env"
chmod 600 "$APP/.env"

# ── 2. systemd ─────────────────────────────────────────────────────────────
echo ""
echo "==> [2/5] Installing the systemd service"
cp "$APP/deploy/systemd/jobspace.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable jobspace
echo "    Installed and enabled (not started yet — .env may need editing)."

# ── 3. Domain into the nginx config ─────────────────────────────────────────
echo ""
echo "==> [3/5] Preparing the nginx config for $DOMAIN"
# One substitution is enough: the config uses the bare placeholder
# `jobspace.example.com` everywhere, including inside the `www.` names, so
# replacing it wholesale yields `jobspace.ng` and `www.jobspace.ng`.
sed -e "s/jobspace\.example\.com/$DOMAIN/g" \
    "$APP/deploy/nginx/jobspace.conf" > /etc/nginx/conf.d/jobspace.conf
echo "    Written to /etc/nginx/conf.d/jobspace.conf"
echo "    Confirm the server_name lines say $DOMAIN before reloading:"
echo "      grep -n server_name /etc/nginx/conf.d/jobspace.conf"

# ── 4. Permissions ─────────────────────────────────────────────────────────
echo ""
echo "==> [4/5] Fixing directory permissions"
# useradd made /var/www/jobspace mode 700, so nginx — a different user — cannot
# traverse into it and every static file would 403 while the app looked fine.
chmod 755 /var/www "$APP"
# The app writes staticfiles/ and media/ as `jobspace`; nginx only needs read.
chmod -R a+rX "$APP/static" "$APP/templates" 2>/dev/null || true

# ── 5. Start and report ────────────────────────────────────────────────────
echo ""
echo "==> [5/5] Starting the service"
# This runs migrate + collectstatic. If DATABASE_URL is still CHANGE_ME the
# migrations will fail — that is expected and is reported below, not hidden.
systemctl start jobspace || true
sleep 3

echo ""
echo "=============================================="
echo " Result"
echo "=============================================="
systemctl is-active jobspace >/dev/null 2>&1 \
    && echo " jobspace service: RUNNING" \
    || echo " jobspace service: NOT RUNNING (see the log below)"

echo ""
echo "---- Last 30 lines of the log ----"
journalctl -u jobspace -n 30 --no-pager 2>/dev/null || true

echo ""
echo "---- Is gunicorn listening? ----"
ss -lntp 2>/dev/null | grep 8010 || echo "  nothing on 8010 yet"

echo ""
echo "=============================================="
echo " NEXT STEPS"
echo "=============================================="
cat <<'EOS'
 1. Fix DATABASE_URL if it still says CHANGE_ME:
      nano /var/www/jobspace/.env
    Then:  systemctl restart jobspace

 2. Fix the permissions for files the app just created:
      chmod -R a+rX /var/www/jobspace/staticfiles /var/www/jobspace/media

 3. Check nginx config, THEN reload (never restart):
      nginx -t && systemctl reload nginx
    Confirm your other two sites are untouched:
      ls -l /etc/nginx/conf.d/

 4. Get the certificate (needs DNS already pointing here):
      certbot --nginx -d YOURDOMAIN -d www.YOURDOMAIN

 5. Verify: site loads, stylesheet loads, sign in works, CV upload works,
    and BOTH other sites still load.
EOS
echo ""
echo "SECURITY: uploaded CVs are currently public to anyone with the URL,"
echo "and FLUTTERWAVE_WEBHOOK_HASH must be set before taking payments."
echo "Both are explained in deploy/DEPLOY.md."
